language: node_js

node_js:
  - 'stable'

before_install:
  - npm install

script:
  - karma start --browsers Firefox --single-run

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - "node_modules"
